[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build"

[deploy]
startCommand = "pnpm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.build]
cmds = [
    "pnpm install",
    "pnpm run build"
]

[phases.deploy]
cmd = "pnpm start" 