[build]
builder = "nixpacks"
buildCommand = "pnpm install && pnpm run build"

[deploy]
startCommand = "pnpm start"

[phases.setup]
nixPkgs = ["nodejs", "pnpm"]

[phases.build]
cmds = [
    "pnpm install",
    "pnpm run build"
]

[phases.deploy]
cmd = "pnpm start" 